accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('create-user/',views.register_user_view,name='register'),
    path('user/change-password/',views.changepassword,name='changepassword'),
    path('user/profile/view/',views.user_profile_view,name='userprofile'),
   

    #Users Views
    path('users/all',views.users_list,name='users'),
    path('users/<int:id>/block',views.users_block,name='userblock'),
    path('users/<int:id>/unblock',views.users_unblock,name='userunblock'),
    path('users/blocked/all',views.users_blocked_list,name='erasedusers'),


]

dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),

    # Employee
    path('employees/all/',views.dashboard_employees,name='employees'),
    path('all_leaves', views.all_leaves, name = 'all_leaves'),
    path('employee/create/',views.dashboard_employees_create,name='employeecreate'),
    path('employee/profile/<int:id>/',views.dashboard_employee_info,name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',views.employee_edit_data,name='edit'),
    path('leave_policy',views.leave_policy,name='leave_policy'),
    # path('emergency/update/<int:id>',views.dashboard_emergency_update,name='emergencyupdate'),

    # # Family
    # path('family/create/',views.dashboard_family_create,name='familycreate'),
    # path('family/edit/<int:id>',views.dashboard_family_edit,name='familyedit'),
    
    # #Bank
    # path('bank/create/',views.dashboard_bank_create,name='bankaccountcreate'),

    #---work-on-edit-view------#
    # path('bank/edit/<int:id>/',views.employee_bank_account_update,name='accountedit'),
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),
    # BIRTHDAY ROUTE
    # path('birthdays/all/',views.birthday_this_month,name='birthdays'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls',namespace='accounts')),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/forms.py
from django import forms
from employee.models import Role,Department,Employee
from django.contrib.auth.models import User


# EMPLoYEE
class EmployeeCreateForm(forms.ModelForm):
	employeeid = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'please enter 5 characters without RGL or slashes eg. A0025'}))
	image = forms.ImageField(widget=forms.FileInput(attrs={'onchange':'previewImage(this);'}))
	birthday = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
	startdate = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
	dateissued = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
	class Meta:
		model = Employee
		exclude = ['is_blocked','is_deleted','created','updated']
		widgets = {
				'bio':forms.Textarea(attrs={'cols':5,'rows':5})
		}

leave/forms.py
from django import forms
from .models import Leave
import datetime

class LeaveCreationForm(forms.ModelForm):
	reason = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}))
	startdate = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
	enddate = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
	class Meta:
		model = Leave
		exclude = ['user','defaultdays','hrcomments','status','is_approved','updated','created']



	def clean_enddate(self):
		enddate = self.cleaned_data['enddate']
		startdate = self.cleaned_data['startdate']
		today_date = datetime.date.today()

		if (startdate or enddate) < today_date:# both dates must not be in the past
			raise forms.ValidationError("Selected dates are incorrect,please select again")

		elif startdate >= enddate:# TRUE -> FUTURE DATE > PAST DATE,FALSE other wise
			raise forms.ValidationError("Selected dates are wrong")

		return enddate

templates/_layout.html
{% load static %}

{% load humanize %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Dashboard - ATA Freight | {% block title %} {{ title }} {% endblock %}</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <meta name="author" content="Mike Edward <Fullstack Developer/>,mail - edward.mike.anaryo@gmail.com">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Anton|Russo+One" rel="stylesheet">

    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'css/light-bootstrap-dashboard.css' %}" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'css/demo.css' %}" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

</head>
<body>


    <style type="text/css">

        .title-h3{
        font-weight: bold;
        font-variant: petite-caps;
    }


     .sidebar{
    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
     box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2); 
     transition: all 400ms ease-in;
    }
    
    .sidebar:hover{
        -webkit-box-shadow: 0 8px 17px 2px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2);
    box-shadow: 0 8px 17px 2px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2);
    }


    .shadow{
        box-shadow:0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
     }

     a.simple-text{
        font-family: 'Russo One', sans-serif;
     }

      a.simple-text > span{
        font-size: 13px !important;
      }

      .logo a{
        font-family: 'Luckiest Guy', cursive;
      }

    .sub-title{
        vertical-align: -webkit-baseline-middle;
        font-size: 12px;
        font-family: 'Luckiest Guy', cursive;
    }


    tr td{
        font-variant: petite-caps;
    }

    {% block stylesheet %}
     
     
    {% endblock %}
    </style>

<div class="wrapper">
    <div class="sidebar" data-color="blue" data-image="{% static 'img/sidebar-1.jpg' %}">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    ATA Freight <span>HRM</span>
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <a href="{% url 'dashboard:dashboard' %}">
                        <i class="pe-7s-graph"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="">
                    <a href="/">
                        <i class="pe-7s-home"></i>
                        <p>Home</p>
                    </a>
                </li>
                
                {% if request.user.is_superuser and request.user.is_staff %}
                <li>
                    <a href="{% url 'dashboard:employees' %}">
                        <i class="pe-7s-users"></i>
                        <p>Employee</p>
                    </a>
                </li>
                {% endif %}

                <li>
                    {% if request.user.is_superuser %}<a href="{% url 'dashboard:leaveslist' %}">{% else %}<a href="{% url 'dashboard:staffleavetable' %}"> {% endif %}
                        <i class="pe-7s-news-paper"></i>
                        <p>Leave</p>
                    </a>
                </li>
                
            </ul>
    	</div>


    </div>

    <div class="main-panel">
    <!--EVERY APP DEFINES ITS ROUTES  -->
    {% block navheader %}
        {% include 'includes/navheader_default.html' %}
    {% endblock %}
    <!-- NAVHEADER -->       

        
    <!--CONTENTS-->
    {% block content %}
    <section class="content">
        <section class="container-fluid">
                


        </section> <!-- /container -->           
     </section>
    {% endblock %}
    <!--/CONTENTS-->

        
        
    </div>
</div>


</body>



    <!--   Core JS Files   -->
    <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="{% static 'js/chartist.min.js' %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'js/bootstrap-notify.js' %}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="{% static 'js/light-bootstrap-dashboard.js' %}"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="{% static 'js/demo.js' %}"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript">
        {% block extrajs%}

 

        {% endblock %}
    </script>

<script type="text/javascript">


    function previewImage(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('.prev-holder .prev-avatar').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    
    $(document).ready(function(){

        $('.refresh-page').click(function(){
            /*Script refreshes the page*/
            console.log('refresh page clicked !!!');
            location.reload(true);

        });


        $( "#id_birthday,#id_dateissued,#id_startdate,#id_enddate" ).datepicker({
            dateFormat: 'yy-mm-dd'
        });


    });
    
	</script>

</html>

templates/base.html
{%load static%}
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="description"
    content="Chameleon Admin is a modern Bootstrap 4 webapp &amp; admin dashboard html template with a large number of components, elegant design, clean and organized code.">
  <meta name="keywords"
    content="admin template, Chameleon admin template, dashboard template, gradient admin template, responsive admin template, webapp, eCommerce dashboard, analytic dashboard">
  <meta name="author" content="ThemeSelect">
  <title>
    {%block tittle%}
    {%endblock%}
  </title>
  
 
  <link href="https://fonts.googleapis.com/css?family=Muli:300,300i,400,400i,600,600i,700,700i%7CComfortaa:300,400,700"
    rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>


  <!-- BEGIN: Vendor CSS-->
  <link rel="stylesheet" type="text/css" href="{%static 'css3/vendors.min.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css3/switchery.min.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css3/switch.min.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css3/palette-switch.min.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css3/chartist.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css3/chartist-plugin-tooltip.css'%}">
  <!-- END: Vendor CSS-->

  <!-- BEGIN: Theme CSS-->
  <link rel="stylesheet" type="text/css" href="{%static 'css3/bootstrap.min.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css3/bootstrap-extended.min.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css3/colors.min.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css3/components.min.css'%}">
  <!-- END: Theme CSS-->

  <!-- BEGIN: Page CSS-->
  <link rel="stylesheet" type="text/css" href="{%static 'css3/vertical-menu.min.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css3/palette-gradient.min.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css3/palette-gradient.min.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css3/chat-application.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css3/dashboard-analytics.min.css'%}">
  <!-- END: Page CSS-->

  <!-- BEGIN: Custom CSS-->
  <link rel="stylesheet" type="text/css" href="{%static 'css3/style.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'css/messages.css'%}">
  <!-- END: Custom CSS-->

</head>
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="vertical-layout vertical-menu 2-columns   fixed-navbar" data-open="click" data-menu="vertical-menu"
  data-color="bg-gradient-x-purple-blue" data-col="2-columns">

  <!-- BEGIN: Header-->
  <nav
    class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-light">
    <div class="navbar-wrapper">
      <div class="navbar-container content">
        <div class="collapse navbar-collapse show" id="navbar-mobile">
          <ul class="nav navbar-nav mr-auto float-left">
            <li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs"
                href="#"><i class='bx bx-menu font-large-1'></i></a></li>
            <li class="nav-item d-none d-md-block"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i
                  class='bx bx-menu font-large-1'></i></a></li>
            <li class="nav-item d-none d-md-block"><a class="nav-link nav-link-expand" href="#"><i
                  class='bx bx-fullscreen font-large-1'></i></a></li>
          </ul>
          <ul class="nav navbar-nav float-right">


            <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link" href="#"
                data-toggle="dropdown"> <span class="avatar avatar-online"><img
                    src="{%static 'images3/avatar1.jpg'%}" alt="avatar"></span></a>
              <div class="dropdown-menu dropdown-menu-right">
                <div class="arrow_box_right"><a class="dropdown-item" href="#"><span class="avatar avatar-online"><img
                        src="{%static 'images3/avatar1.jpg'%}" alt="avatar"><span
                        class="user-name text-bold-700 ml-1">{{request.user.username}}</span></span></a>
                  <div class="dropdown-divider"></div><a class="dropdown-item" href="{%url 'accounts:changepassword'%}"><i
                      class='bx bxs-key font-large-1'></i> change password</a>
                  <div class="dropdown-divider"></div><a class="dropdown-item" href="{%url 'accounts:logout'%}"><i
                      class='bx bx-log-out font-large-1'></i>Logout</a>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <!-- END: Header-->


  <!-- BEGIN: Main Menu-->
  <div class="main-menu menu-fixed menu-light menu-accordion    menu-shadow " data-scroll-to-active="true"
    data-img="{%static 'images3/backgrounds/02.jpg'%}">
    <div class="navbar-header">
      <ul class="nav navbar-nav flex-row">
        <li class="nav-item mr-auto"><a class="navbar-brand" href="index.html"><img class="brand-logo" alt="" src="" />
            <h3 class="brand-text">LMS</h3>
          </a></li>
        <li class="nav-item d-md-none"><a class="nav-link close-navbar"><i class='bx bx-x font-large-1'></i></a></li>
      </ul>
    </div>
    <div class="navigation-background"></div>
    <div class="main-menu-content">
      <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
        <li class=" nav-item"><a href="{%url 'dashboard:dashboard'%}"><i class='bx bx-home-alt font-large-1'></i><span
              class="menu-title" data-i18n="">Dashboard</span>
        </li>
        <li class=" nav-item"><a href="{%url 'accounts:userprofile'%}"><i class='bx bx-user-pin font-large-1'></i><span class="menu-title"
              data-i18n="">Profile</span></a>
        </li>
        {% if request.user.is_superuser%}
        <li class=" nav-item"><a href="#">
          <i class='bx bx-user font-large-1' ></i><span class="menu-title" data-i18n="">Users</span> <span style="margin-left: 3rem; font-size: 1.6rem;"><i style="margin-top: 1rem;" class='bx bx-chevron-down'></i></span></a> 
          <ul class="menu-content">
            <li><a class="menu-item" href="{% url 'accounts:register' %}">Create users</a>
            </li>
            <li><a class="menu-item" href="{% url 'accounts:users' %}">All Users</a>
            </li>
            
          </ul>
        </li>
        {%endif%}
        {%if request.user.is_superuser %}
        <li class=" nav-item"><a href="#">
          <i class='bx bxs-user-detail font-large-1'></i><span class="menu-title" data-i18n="">Employees</span> <span style="margin-left: 3rem; font-size: 1.6rem;"><i style="margin-top: 1rem;" class='bx bx-chevron-down'></i></span></a> 
          <ul class="menu-content">
            <li><a class="menu-item" href="{% url 'dashboard:employeecreate' %}">Add Employee</a>
            </li>
            <li><a class="menu-item" href="{% url 'dashboard:employees' %}">All Eployees</a>
            </li>
            <li><a class="menu-item" href="{% url 'accounts:erasedusers' %}">Blocked Employees</a>
            </li>
          </ul>
        </li>
        {%endif%}
        <li class=" nav-item"><a href="#">
          <i class='bx bxs-plane-alt font-large-1'></i> <span class="menu-title" data-i18n="">Leaves</span> <span style="margin-left: 3rem; font-size: 1.6rem;"><i style="margin-top: 1rem;" class='bx bx-chevron-down'></i></span></a> 
            <ul class="menu-content">
              {% if request.user.is_staff %}
              <li><a class="menu-item" href="{% url 'dashboard:leaveslist' %}">Pending Leaves</a>
              </li>
              <li><a class="menu-item" href="{% url 'dashboard:approvedleaveslist' %}">Approved Leaves</a>
              </li>
              <li><a class="menu-item" href="{% url 'dashboard:leavesrejected' %}">Rejected Leaves</a>
              </li>
              <li><a class="menu-item" href="{% url 'dashboard:canceleaveslist' %}">Cancelled Leaves</a>
              </li>
              {%endif%}
              <li><a class="menu-item" href="{%url 'dashboard:createleave'%}">Apply leave</a>
              </li>
              <li><a class="menu-item" href="{%url 'dashboard:staffleavetable'%}">Your leave history</a>
              </li>
            </ul>
        </li>
        <!-- <li class=" nav-item"><a href="#"><i class='bx bxs-bell-ring font-large-1'></i><span class="menu-title"
              data-i18n="">Notifications</a>
        </li> -->

        
        <!-- <li class=" nav-item"><a href="#"><i class="ft-zap"></i><span class="menu-title" data-i18n=""></span></a>
 
          </li>
          <li class=" nav-item"><a href="#"><i class="ft-aperture"></i><span class="menu-title" data-i18n="">User Interface</span></a>
          </li> -->

      </ul>
    </div>
  </div>
  <!-- END: Main Menu-->


  <!-- BEGIN: Content-->
  <div class="app-content content">
    <div class="content-wrapper">
      <div class="content-wrapper-before"></div>
      <div class="content-header row">
      </div>
      <div class="content-body">
        {%block content%}
        {%endblock%}
         
      </div>

      </div>
    </div>
  </div>
  <!-- END: Content-->


   {%block page_scripts%}
   {%endblock%}
  <!-- BEGIN: Vendor JS-->
  <script src="{%static 'js3/vendors.min.js'%}" type="text/javascript"></script>
  <script src="{%static 'js3/switchery.min.js'%}" type="text/javascript"></script>
  <script src="{%static 'js3/switch.min.js'%}" type="text/javascript"></script>
  <!-- BEGIN Vendor JS-->

  <!-- BEGIN: Page Vendor JS-->
  <script src="{%static 'js3/chartist.min.js'%}" type="text/javascript"></script>
  <script src="{%static 'js3/chartist-plugin-tooltip.min.js'%}" type="text/javascript"></script>
  <!-- END: Page Vendor JS-->

  <!-- BEGIN: Theme JS-->
  <script src="{%static 'js3/app-menu.min.js'%}" type="text/javascript"></script>
  <script src="{%static 'js3/app.min.js'%}" type="text/javascript"></script>
  <script src="{%static 'js3/customizer.min.js'%}" type="text/javascript"></script>
  <script src="{%static 'js3/jquery.sharrre.js'%}" type="text/javascript"></script>
  <!-- END: Theme JS-->

  <!-- BEGIN: Page JS-->
  <script src="{%static 'js3/dashboard-analytics.min.js'%}" type="text/javascript"></script>
  <script src="{%static 'js/messages.js'%}" type="text/javascript"></script>
  <!-- END: Page JS-->
  
</body>
<!-- END: Body-->

</html>