accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('create-user/',views.register_user_view,name='register'),
    path('user/change-password/',views.changepassword,name='changepassword'),
    path('user/profile/view/',views.user_profile_view,name='userprofile'),
   

    #Users Views
    path('users/all',views.users_list,name='users'),
    path('users/<int:id>/block',views.users_block,name='userblock'),
    path('users/<int:id>/unblock',views.users_unblock,name='userunblock'),
    path('users/blocked/all',views.users_blocked_list,name='erasedusers'),


]

dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),

    # Employee
    path('employees/all/',views.dashboard_employees,name='employees'),
    path('all_leaves', views.all_leaves, name = 'all_leaves'),
    path('employee/create/',views.dashboard_employees_create,name='employeecreate'),
    path('employee/profile/<int:id>/',views.dashboard_employee_info,name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',views.employee_edit_data,name='edit'),
    path('leave_policy',views.leave_policy,name='leave_policy'),
    # path('emergency/update/<int:id>',views.dashboard_emergency_update,name='emergencyupdate'),

    # # Family
    # path('family/create/',views.dashboard_family_create,name='familycreate'),
    # path('family/edit/<int:id>',views.dashboard_family_edit,name='familyedit'),
    
    # #Bank
    # path('bank/create/',views.dashboard_bank_create,name='bankaccountcreate'),

    #---work-on-edit-view------#
    # path('bank/edit/<int:id>/',views.employee_bank_account_update,name='accountedit'),
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),
    # BIRTHDAY ROUTE
    # path('birthdays/all/',views.birthday_this_month,name='birthdays'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls',namespace='accounts')),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import Q
import datetime
from django.core.mail import send_mail
from django.contrib import messages
from django.urls import reverse
from employee.forms import EmployeeCreateForm
from leave.models import Leave
from employee.models import *
from leave.forms import LeaveCreationForm
from django.http import HttpResponse
from django.template.loader import render_to_string
from weasyprint import HTML
from django.core.mail import send_mail


def dashboard(request):
	
	'''
	Summary of all apps - display here with charts etc.
	eg.lEAVE - PENDING|APPROVED|RECENT|REJECTED - TOTAL THIS MONTH or NEXT MONTH
	EMPLOYEE - TOTAL | GENDER 
	CHART - AVERAGE EMPLOYEE AGES
	'''
	dataset = dict()
	user = request.user

	if not request.user.is_authenticated:
		return redirect('accounts:login')

	employees = Employee.objects.all()
	dept = Department.objects.all()
	leaves = Leave.objects.all_pending_leaves()
	all_leaves = Leave.objects.all()
	leave_policy = Leave_policy.objects.all()
	
	staff_leaves = Leave.objects.filter(user = user)
	emp = Employee.objects.filter(user=user).first()
	
	taken = 160 - emp.leave_balance
	dataset['employees'] = employees
	dataset['leaves'] = leaves
	
	dataset['staff_leaves'] = staff_leaves
	context = {
		"all_leaves":all_leaves,
		"dept":dept,
		"taken":taken,
		"employees":employees,
		"leaves":leaves,
		"staff_leaves":staff_leaves,
		"emp":emp,
		"leave_policy":leave_policy
	}

	return render(request,'dashboard/dashboard_index.html',context)


def leave_policy(request):
    leave_policy = Leave_policy.objects.all()
    return render(request, 'dashboard/dashboard_index.html',{"leave_policy":leave_policy})


def dashboard_employees(request):
	if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
		return redirect('/')

	dataset = dict()
	departments = Department.objects.all()
	employees = Employee.objects.all()

	#pagination
	query = request.GET.get('search')
	if query:
		employees = employees.filter(
			Q(firstname__icontains = query) |
			Q(lastname__icontains = query)
		)



	paginator = Paginator(employees, 10) #show 10 employee lists per page

	page = request.GET.get('page')
	employees_paginated = paginator.get_page(page)



	blocked_employees = Employee.objects.all_blocked_employees()

	context = {
		"departments":departments,
		"employees":employees,
		"paginator":paginator,
		"employees_paginated":employees_paginated,
		"blocked_employees":blocked_employees
		}


	return render(request,'dashboard/employee_app.html',context)




def dashboard_employees_create(request):
	if not (request.user.is_authenticated and request.user.is_superuser):
		return redirect('/')

	if request.method == 'POST':
		form = EmployeeCreateForm(request.POST,request.FILES)
		if form.is_valid():
			instance = form.save(commit = False)
			user = request.POST.get('user')
			assigned_user = User.objects.get(id = user)

			instance.user = assigned_user

			instance.title = request.POST.get('title')
			instance.image = request.FILES.get('image')
			instance.firstname = request.POST.get('firstname')
			instance.lastname = request.POST.get('lastname')
			instance.othername = request.POST.get('othername')
			
			instance.birthday = request.POST.get('birthday')

			role = request.POST.get('role')
			role_instance = Role.objects.get(id = role)
			instance.role = role_instance

			instance.startdate = request.POST.get('startdate')
			instance.employeetype = request.POST.get('employeetype')
			instance.employeeid = request.POST.get('employeeid')
			instance.dateissued = request.POST.get('dateissued')

			
			messages.error(request,'employee added successfully ',extra_tags = 'alert alert-success alert-dismissible show')
			instance.save()
			return  redirect('dashboard:employees')
		else:
			messages.error(request,'Trying to create dublicate employees with a single user account ',extra_tags = 'alert alert-warning alert-dismissible show')
			return redirect('dashboard:employeecreate')


	dataset = dict()
	form = EmployeeCreateForm()
	dataset['form'] = form
	dataset['title'] = 'register employee'
	return render(request,'dashboard/employee_create.html',dataset)


def employee_edit_data(request,id):
	if not (request.user.is_authenticated and request.user.is_superuser):
		return redirect('/')
	employee = get_object_or_404(Employee, id = id)
	if request.method == 'POST':
		form = EmployeeCreateForm(request.POST or None,request.FILES or None,instance = employee)
		if form.is_valid():
			instance = form.save(commit = False)

			user = request.POST.get('user')
			assigned_user = User.objects.get(id = user)

			instance.user = assigned_user

			instance.image = request.FILES.get('image')
			instance.firstname = request.POST.get('firstname')
			instance.lastname = request.POST.get('lastname')
			instance.othername = request.POST.get('othername')
			
			instance.birthday = request.POST.get('birthday')

			religion_id = request.POST.get('religion')
			religion = Religion.objects.get(id = religion_id)
			instance.religion = religion

			nationality_id = request.POST.get('nationality')
			nationality = Nationality.objects.get(id = nationality_id)
			instance.nationality = nationality

			department_id = request.POST.get('department')
			department = Department.objects.get(id = department_id)
			instance.department = department


			instance.hometown = request.POST.get('hometown')
			instance.region = request.POST.get('region')
			instance.residence = request.POST.get('residence')
			instance.address = request.POST.get('address')
			instance.education = request.POST.get('education')
			instance.lastwork = request.POST.get('lastwork')
			instance.position = request.POST.get('position')
			instance.ssnitnumber = request.POST.get('ssnitnumber')
			instance.tinnumber = request.POST.get('tinnumber')

			role = request.POST.get('role')
			role_instance = Role.objects.get(id = role)
			instance.role = role_instance

			instance.startdate = request.POST.get('startdate')
			instance.employeetype = request.POST.get('employeetype')
			instance.employeeid = request.POST.get('employeeid')
			instance.dateissued = request.POST.get('dateissued')

			# now = datetime.datetime.now()
			# instance.created = now
			# instance.updated = now

			instance.save()
			messages.success(request,'Account Updated Successfully !!!',extra_tags = 'alert alert-success alert-dismissible show')
			return redirect('dashboard:employees')

		else:

			messages.error(request,'Error Updating account',extra_tags = 'alert alert-warning alert-dismissible show')
			return HttpResponse("Form data not valid")

	dataset = dict()
	form = EmployeeCreateForm(request.POST or None,request.FILES or None,instance = employee)
	dataset['form'] = form
	dataset['title'] = 'edit - {0}'.format(employee.get_full_name)
	return render(request,'dashboard/employee_create.html',dataset)





def dashboard_employee_info(request,id):
	if not request.user.is_authenticated:
		return redirect('/')
	
	employee = get_object_or_404(Employee, id = id)
	
	
	dataset = dict()
	dataset['employee'] = employee
	dataset['title'] = 'profile - {0}'.format(employee.get_full_name)
	return render(request,'dashboard/employee_detail.html',dataset)





# ---------------------LEAVE-------------------------------------------



def leave_creation(request):
	if not request.user.is_authenticated:
		return redirect('accounts:login')

	employee = Employee.objects.get(user=request.user)
	if request.method == 'POST':
		form = LeaveCreationForm(data = request.POST)
		if form.is_valid():
			instance = form.save(commit = False)
			user = request.user
			instance.user = user
			leave_days = instance.leave_days
			if leave_days > employee.leave_balance:
				messages.error(request,'your leaves requests exceeded your yearly balance',extra_tags = 'alert alert-warning alert-dismissible show')	
			else:
				instance.save()
				send_mail(
                'New leave request',
                f"There is a new leave request visit the system to view",
                'uccdodoma@gmail.com',
                ['rajabtawfiq59@gmail.com'],
                fail_silently=False,
            	)
				messages.info(request,'Leave Request Sent,wait for Managers response',extra_tags = 'alert     alert-success alert-dismissible show')
			return redirect('dashboard:createleave')
		else:
			messages.error(request,'failed to Request a Leave,please check entry dates',extra_tags = 'alert alert-warning alert-dismissible show')
		return redirect('dashboard:createleave')


	dataset = dict()
	form = LeaveCreationForm()
	dataset['form'] = form
	dataset['title'] = 'Apply for Leave'
	return render(request,'dashboard/create_leave.html',dataset)
	



def leaves_list(request):
	if not (request.user.is_staff and request.user.is_superuser):
		return redirect('/')
	leaves = Leave.objects.all_pending_leaves()
	return render(request,'dashboard/leaves_recent.html',{'leave_list':leaves,'title':'leaves list - pending'})



def leaves_approved_list(request):
	if not (request.user.is_staff):
		return redirect('/')
	leaves = Leave.objects.all_approved_leaves() #approved leaves -> calling model manager method
	return render(request,'dashboard/leaves_approved.html',{'leave_list':leaves,'title':'approved leave list'})



def leaves_view(request, id):
    if not request.user.is_authenticated:
        return redirect('/')

    leave = get_object_or_404(Leave, id=id)
    employee = Employee.objects.filter(user=leave.user).first()

    # Generate the absolute URL for the employee image
    employee_image_url = request.build_absolute_uri(employee.image.url)

    # Pass the absolute image URL to the context
    context = {
        'leave': leave,
        'employee': employee,

templates/dashboard/employee_app.html
{%extends 'base.html'%}
        

{% block tittle %} employees {% endblock %}

{% load crispy_forms_tags %}


  

 <!--CONTENTS-->
 {% block content %}
 <div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card" style="height: auto; padding: 1rem;">
            <div class="card-header">
                <h4 class="card-title">Change Password</h4>
                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a href="{%url 'dashboard:dashboard'%}">
                            <button type="button" class="btn btn-glow btn-round btn-bg-gradient-x-red-pink">Back to Dashboard</button>
                        </a></li>
                    </ul>
                </div>
            </div>
            <div class="card-content collapse show">
                <div class="card-body">
					<section class="row" style = "height:2rem">
						<section class="col col-sm-8 offset-sm-2">
					
							{% if messages %}
							{% for message in messages %}
							<div {% if message.tags %} class="{{ message.tags}}" {% endif %} id="message-container">
								<h4 style="color: white;">{{ message }}</h4>
								<button type="button" class="close" id="override-start" data-dismiss="alert"
									aria-label="Close"><span aria-hidden="true">&times;</span>
								</button>
							</div>
							{% endfor %}
							{% endif %}
						</section>
					</section>
					<!-- <div class="container"> -->
					<section class="row margin-bottom">
						<div class="container-fluid">
						<section class="col-lg-4 col-md-4 col-sm-12">
							<div class="employee-box sec-box">
								<a href="">
								<span>Employees</span>
								</a>
								<span class="count-object">{{ all_employees.count }}</span> 
							</div>
						</section>
						
					
					</section> 
					<div class="row">
						<div class="table-responsive">
							<div class="table-shadow">
								<div class="text-center table-description">
									<h4 class="title-h3">All Employees</h4>
								</div>
								<div class="container-fluid">
									<div class="row">
										 <div class="download-print-action">
											  Download Excel | Pdf | Print
										</div>
									</div>
								</div>
								<table class="table">
									  <thead>
										<tr>
										  <th scope="col">Username</th>
										  <th scope="col">Employee (fullname) </th>
										  <th scope="col">Department</th>
										  <th scope="col">Status</th>
										  <th scope="col">Actions</th>
										  <!-- <th scope="col">view</th> -->
										</tr>
									  </thead>
		
									  <tbody>
										  {% for emp in employees %}
										  <tr>
											  <td>{{emp.user.username}}</td>
											  <td>{{ emp.get_full_name }}</td>
											  <td>{{ emp.department }}</td>
											  {% if emp.user.is_active %}
											  <td>active</td>
											  {% else %}
											  <td>inactive</td>
											  {% endif %}
		
											  {%  if emp.user.is_active and emp.user.is_superuser %}
											  <!-- Admin cannot block self -->
											  <td style="font-style:italic;">(admin)</td>
											  {% elif emp.user.is_active %}
											  <td><a href="{% url 'accounts:userblock' emp.user.id %}" title="block user"><i class='bx bx-lock-open-alt font-large-1' ></i></a></td>
											  {% else %}
											  <td><a href="{% url 'accounts:userunblock' emp.user.id %}" title="unblock user"><i class='bx bx-lock-alt font-large-1' ></i></a></td>
											  {% endif %}
											  <!-- <td><a href="{% url 'dashboard:employeeinfo' emp.user.id %}" title="view user"><i class='bx bx-show-alt font-large-1'></i></a></td>    -->
									  </tr>
									   {% endfor %}
									  </tbody>
								</table>
							</div>
						</div>
					</div>
                </div>
            </div>
        </div>
  </div>
 </div>
 {% endblock %}

templates/dashboard/leave_detail_view.html
{%extends 'base.html'%}


{% block tittle %} leave details {% endblock %}

{% block content %}

<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="card" style="height: auto; padding: 1rem;">
     <!-- leave_detail_view.html -->
<div class="row">  
  <div class="col-lg-4 text-center">
      <img src="{{ employee.image.url}}" style="height:200px; width:200px; border-radius:50%;" class="img-fluid rounded-circle-image">
  </div>
  <div class="col-lg-8 col-md-12 col-sm-12">
    
      <div class="list-group" id="list-tab" role="tablist">
        <section class="row" style = "height:2rem; z-index: 10;" >
            <section class="col col-sm-8 offset-sm-2">
                
              {% if messages %}
              {% for message in messages %}
              <div {% if message.tags %} class="{{ message.tags}}" {% endif %} id="message-container">
                  <h4 style="color: white; text-align: center;">{{ message }}</h4>
              </div>
              {% endfor %}
              {% endif %}
        
            </section>
        </section>
          <a class="list-group-item list-group-item-action" id="list-home-list" role="tab" aria-controls="">
              <span>Employee</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ employee.get_full_name }}</div>
          </a>
          <a class="list-group-item list-group-item-action" id="list-profile-list" role="tab" aria-controls="">
              <span>Start Date</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ leave.startdate }}</div>
          </a>
          <a class="list-group-item list-group-item-action" id="list-messages-list" role="tab" aria-controls="">
              <span>End Date</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ leave.enddate }}</div>
          </a>
          <a class="list-group-item list-group-item-action" id="list-settings-list" role="tab" aria-controls="">
              <span>Duration</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ leave.leave_days }}</div>
          </a>
          <a class="list-group-item list-group-item-action" id="list-settings-list" role="tab" aria-controls="">
              <span>Type</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ leave.leavetype }}</div>
          </a>
          <a class="list-group-item list-group-item-action" id="list-settings-list" role="tab" aria-controls="">
              <span>Reason</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ leave.reason }}</div>
          </a>
          <a class="list-group-item list-group-item-action" id="list-settings-list" role="tab" aria-controls="">
              <span>Status</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ leave.status }}</div>
          </a>
      </div>

      <!-- Superuser and admin actions -->
      {% if request.user.is_staff %}
      <div class="row">
          <div class="col col-lg-4 col-sm-12 col-lg-offset-7 text-center">
              <div class="btn-group btn-group-justified">
                    {%if leave.status == 'rejected'%}
                    {%else%}
                  {% if leave.leave_approved %}
                  <a href="{% url 'dashboard:userleaveunapprove' leave.id %}" class="btn btn-primary">UNAPPROVE</a>
                  {% else %}
                  <a href="{% url 'dashboard:userleaveapprove' leave.id %}" class="btn btn-primary">APPROVE</a>
                  {% endif %}
                  {% comment %} <a href="{% url 'dashboard:userleavecancel' leave.id %}" class="btn btn-info">CANCEL</a> {% endcomment %}
                  
                  <a href="{% url 'dashboard:reject' leave.id %}" class="btn btn-warning">REJECT</a>
                  {%endif%}
                  <a href="?format=pdf" class="btn btn-secondary">Download PDF</a>
              </div>
          </div>
      </div>
      {% else %}
      {% if leave.status == 'cancelled' %}
      <a href="{% url 'dashboard:dashboard' %}" class="btn btn-info">Back to dashboard</a>
      {% else %}
      {% if leave.leave_approved %}
      <a href="{% url 'dashboard:dashboard' %}" class="btn btn-info">Back to dashboard</a>
      {% else %}
      {%if request.user.is_superuser%}
      {%else%}
      <a href="{% url 'dashboard:userleavecancel' leave.id %}" class="btn btn-danger">CANCEL</a>
      {%endif%}
      {%endif%}
      {% endif %}
      {% endif %}

  </div>
</div>
<span style="font-size: 13px;padding-left: 1rem;" class="pull-left">Created {{ leave.created }}</span>

    
    </div>
  </div>
</div>
{% endblock %}

templates/dashboard/rejection_form.html
{%extends 'base.html'%}


{% block tittle %} leave details {% endblock %}

{% block content %}

<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="card" style="height: auto; padding: 1rem;">
     <!-- leave_detail_view.html -->
<div class="row">  
  <div class="col-lg-4 text-center">
      <img src="{{ employee.image.url}}" style="height:200px; width:200px; border-radius:50%;" class="img-fluid rounded-circle-image">
  </div>
  <div class="col-lg-8 col-md-12 col-sm-12">
    
      <div class="list-group" id="list-tab" role="tablist">
        <section class="row" style = "height:2rem; z-index: 10;" >
            <section class="col col-sm-8 offset-sm-2">
                
              {% if messages %}
              {% for message in messages %}
              <div {% if message.tags %} class="{{ message.tags}}" {% endif %} id="message-container">
                  <h4 style="color: white; text-align: center;">{{ message }}</h4>
              </div>
              {% endfor %}
              {% endif %}
        
            </section>
        </section>
          <a class="list-group-item list-group-item-action" id="list-home-list" role="tab" aria-controls="">
              <span>Employee</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ employee.get_full_name }}</div>
          </a>
          <a class="list-group-item list-group-item-action" id="list-profile-list" role="tab" aria-controls="">
              <span>Start Date</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ leave.startdate }}</div>
          </a>
          <a class="list-group-item list-group-item-action" id="list-messages-list" role="tab" aria-controls="">
              <span>End Date</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ leave.enddate }}</div>
          </a>
          <a class="list-group-item list-group-item-action" id="list-settings-list" role="tab" aria-controls="">
              <span>Duration</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ leave.leave_days }}</div>
          </a>
          <a class="list-group-item list-group-item-action" id="list-settings-list" role="tab" aria-controls="">
              <span>Type</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ leave.leavetype }}</div>
          </a>
          <a class="list-group-item list-group-item-action" id="list-settings-list" role="tab" aria-controls="">
              <span>Reason</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ leave.reason }}</div>
          </a>
          <a class="list-group-item list-group-item-action" id="list-settings-list" role="tab" aria-controls="">
              <span>Status</span>
              <div style="font-size: 1.5rem; font-weight: 600;">{{ leave.status }}</div>
          </a>
      </div>

      <!-- Superuser and admin actions -->
      {% if request.user.is_staff %}
      <div class="row">
          <div class="col col-lg-4 col-sm-12 col-lg-offset-7 text-center">
              <div class="btn-group btn-group-justified">
                  {% if leave.leave_approved %}
                  <a href="{% url 'dashboard:userleaveunapprove' leave.id %}" class="btn btn-primary">UNAPPROVE</a>
                  {% else %}
                  <a href="{% url 'dashboard:userleaveapprove' leave.id %}" class="btn btn-primary">APPROVE</a>
                  {% endif %}
                  {% comment %} <a href="{% url 'dashboard:userleavecancel' leave.id %}" class="btn btn-info">CANCEL</a> {% endcomment %}
                  <a href="{%url 'dashboard:reject' leave.id%}" id="show-rejection-reason-btn" class="btn btn-warning">REJECT</a>
                  <a href="?format=pdf" class="btn btn-secondary">Download PDF</a>
              </div>
          </div>
      </div>
      {% else %}
      {% if leave.status == 'cancelled' %}
      <a href="{% url 'dashboard:dashboard' %}" class="btn btn-info">Back to dashboard</a>
      {% else %}
      {% if leave.leave_approved %}
      <a href="{% url 'dashboard:dashboard' %}" class="btn btn-info">Back to dashboard</a>
      {% else %}
      <a href="{% url 'dashboard:userleavecancel' leave.id %}" class="btn btn-danger">CANCEL</a>
      {%endif%}
      {% endif %}
      {% endif %}

  </div>
</div>
<span style="font-size: 13px;padding-left: 1rem;" class="pull-left">Created {{ leave.created }}</span>

    
    </div>
  </div>
</div>

{% if request.user.is_staff %}
<div class="row" id="rejection-reason-container" style="display: none;">
{% comment %} {%include 'dashboard/rejection_form.html'%} {% endcomment %}
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="rejection_reason">Reason for Rejection:</label>
        <textarea id="rejection_reason" name="rejection_reason" class="form-control" required></textarea>
    </div>
    <!-- Use a proper button to submit the form -->
    <button type="submit" class="btn btn-danger">Reject Leave</button>
</form>
</div>
{%endif%}
{% endblock %}

{%block page_scripts%}


{% comment %} <script>
    // JavaScript to toggle the visibility of the rejection reason textarea
    document.getElementById('show-rejection-reason-btn').addEventListener('click', function() {
        var rejectionReasonContainer = document.getElementById('rejection-reason-container');
        if (rejectionReasonContainer.style.display === 'none') {
            rejectionReasonContainer.style.display = 'block';
        } else {
            rejectionReasonContainer.style.display = 'none';
        }
    });
</script> {% endcomment %}
{%endblock%}